version: '2'

services:
  app:
    build: .
    ports:
      - 9000:9000
    links:
      - postgres:postgres
      - redis:redis
    environment:
      SENTRY_DOCKER_DO_DB_CHECK: 1
      SENTRY_SECRET_KEY: eeng5pe3Ahh9kaifoibi5Aexepheey6Y
      SENTRY_ALLOW_REGISTRATION: 1
      SENTRY_INITIAL_TEAM: Sentry
      SENTRY_INITIAL_PROJECT: Internal

      SENTRY_SINGLE_ORGANIZATION: 0
      SENTRY_REDIS_HOST: redis

      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: secret
    depends_on:
      - redis
      - postgres

  postgres:
    image: library/postgres:9.4
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: sentry
      POSTGRES_DB: sentry

  redis:
    image: library/redis:2.8
